tracks:
    - id: 1
      name: My Gene Models Track
      type: ModelsTrack
      path: Gene Models
      data: /features/lane/1
      showControls: true
      height: 80
    - id: 2
      name: Repeats
      type: MaskTrack
      path: Repeats
      data: /features/lane/2
      showControls: true
      minHeight: 20
      maxHeight: 60
      height: 20
      single: true
    - id: 3
      name: Reads
      type: ReadsTrack
      path: Reads
      data: /features/lane/3
      maxHeight: 500
      height: 70
#A list of tracks that will be active by default (use the ID of the track)
active:
    - 1
    - 2
    - 3
#genome - the service that knows about the genome
genome: genomes/1
# bookmarks - the service that keeps the bookmarks
bookmarks: 
#css - a list of services or locations for css (optional)
stylesheets: 
      - id: simple
        name: simple CSS
        href: stylesheets/simple.css
        active: true
#where to focus the view on start up
location:
    assembly: Chr1
    position: 4000
    bases: 20
    pixels: 1
#site administrator information (optional)    
admin:
    name: 'Mick Jagger'
    email: 'Mick@streetfightingman.ac.uk'
    notes: 'moves well'
    citation: 'a reference'